app/models/user.py
from app.services.database import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)

app/__init__.py
from flask import Flask
from .routes import register as route_register
from .services import register as service_register
from .config import DevConfig, ProdConfig

def create_app():
    app = Flask(__name__,
                static_folder='../static',
                template_folder='../templates')

    app.config.from_object(DevConfig)
    service_register(app)
    route_register(app)

    return app

app/config/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os, secrets


class Config:
    load_dotenv()
    DEBUG = True
    SECRET_KEY = secrets.token_hex(32)
    SQLALCHEMY_DATABASE_URI = 'sqlite:///app.db'


class DevConfig(Config):
    DEBUG = True


class ProdConfig(Config):
    DEBUG = False

app/routes/__init__.py
import os
import importlib
from flask import Flask, Blueprint


def register(app: Flask):
    current_dir = os.path.dirname(__file__)

    for filename in os.listdir(current_dir):
        if filename.endswith(".py") and filename != "__init__.py":
            module_name = f"{__name__}.{filename[:-3]}"
            module = importlib.import_module(module_name)

            bp = getattr(module, "bp", None)
            if isinstance(bp, Blueprint):
                app.register_blueprint(bp)
                print(f'> Registered \'{module_name}\' routes collection')

app/routes/basic.py
from flask import Blueprint, render_template
from app.models.user import User
from app.services.database import db

bp = Blueprint('basic', __name__)


@bp.route('/')
def home():
    return render_template('index.html')


@bp.route('/users')
def users():
    users = User.query.all()
    return render_template('users.html', users=users)


@bp.route('/users/add/<name>')
def add_user(name):
    new_user = User(name=name)
    db.session.add(new_user)
    db.session.commit()
    return render_template('user_add.html', name=name)

app/services/__init__.py
import os
import importlib
from flask import Flask


def register(app: Flask):
    current_dir = os.path.dirname(__file__)

    for filename in os.listdir(current_dir):
        if filename.endswith(".py") and filename != "__init__.py":
            module_name = f"{__name__}.{filename[:-3]}"
            module = importlib.import_module(module_name)

            func = getattr(module, "register", None)
            if callable(func):
                func(app)
                print(f'> Registered \'{module_name}\' service')

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>My Flask Site</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Hello, Flask!</h1>
    <p>This is my Flask website.</p>

    <a href="{{ url_for('basic.users') }}">Get All Users</a>
</body>
</html>

templates/user_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Added</title>
</head>
<body>
    <h1>User {{ name }} added!</h1>
    <a href="{{ url_for('basic.users') }}">Get All Users</a>
    <a href="{{ url_for('basic.home') }}">Home</a>
</body>
</html>

templates/users.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Users List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        h1 {
            margin-bottom: 20px;
        }
        table {
            border-collapse: collapse;
            width: 50%;
        }
        table, th, td {
            border: 1px solid #888;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
    </style>
</head>
<body>
    <h1>Users</h1>
    <a href="{{ url_for('basic.home') }}">Home</a>

    {% if users %}
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <p>No users found.</p>
    {% endif %}
    
</body>
</html>